#################################################################################################
# API STYLES RESULT MANAGEMENT

GET {{host-url}}//styleResult/all

###

#################################################################################################
# API STYLES RESULT MANAGEMENT

GET {{host-url}}//lastResult/all

###

#################################################################################################
# API HORSES MANAGEMENT

GET {{host-url}}//horses/all

###
#################################################################################################
# API CONTRIES MANAGEMENT

GET {{host-url}}//countries/all

###

#################################################################################################
# API RIDERS VIEW MANAGEMENT

GET {{host-url}}//ridersView/all

###
#################################################################################################
# API COMPETITIONS VIEW MANAGEMENT

GET {{host-url}}//competitionsView/all

###
#################################################################################################
# API COMPETITION STYLES VIEW MANAGEMENT

GET {{host-url}}//competitionStyles/all

###

GET {{host-url}}//competitionStyles/1

###
